# Generated by Django 3.2.25 on 2024-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacmangamescore',
            name='level',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
